export {default as Splash} from './Splash';
export {default as Onboarding} from './Onboarding';
export {default as Login} from './Login';
export {default as SignIn} from './SignIn';
export {default as Home} from './Home';
export {default as Home1} from './Home1';
export {default as Edit} from './Edit';
export {default as Wallet} from './Wallet'
export {default as AddWalletScreen} from './AddWalletScreen'
export {default as EditWalletScreen} from './EditWalletScreen'